name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build Application

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get node_modules cache
        uses: actions/cache@v4
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install
        run: yarn install

      - name: Build
        run: yarn build
