name: Lint

on:
  push:
    paths:
      - "packages/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Node.js 14
        uses: actions/setup-node@v2
        with:
          node-version: 14
          cache: "yarn"
          cache-dependency-path: "**/yarn.lock"

      - name: Install
        run: yarn install

      - name: Lint
        run: yarn lintall:check
